In [1]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)


[1 2 3 4 5]


In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
array = np.arange(10)
print(array)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
n=6;
for i in range(0,n,1):
  for j in range(i,0,-1):
    print("*",end=" ")
  print()


* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
#element comparision
a=np.array([1,2,5,4])
b=np.array([6,2,9,4])
print(a==b)

[False  True False  True]


In [ ]:
print(a>b)

[False False False False]


In [ ]:
#array wise comparision
print(np.array_equal(a,b))

False


In [ ]:
c=np.array([1,2,5,4])
print(np.array_equal(a,c))

True


In [ ]:
#logical operator
a=np.array([1,0,0,1],dtype='bool')
b=np.array([0,1,0,1],dtype='bool')
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True False  True]
[False False False  True]


In [ ]:
a=np.arange(1,6,1)
print(a)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[1 2 3 4 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,4])
print(a+b)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
#basic reductions
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [ ]:
y=np.array([[1,2],[3,4]])
print(y)
print("*"*100)
print(y.T)

[[1 2]
 [3 4]]
****************************************************************************************************
[[1 3]
 [2 4]]


In [ ]:
#column wise sum
print(y.sum(axis=0))

[4 6]


In [ ]:
#row wise sum
print(y.sum(axis=1))

[3 7]


In [ ]:
print(y.max())

4


In [ ]:
#indexing of minimum element
print(y.argmax())

3


In [ ]:
#logical reducttions
print(np.all([True,False,False]))

False


In [ ]:
print(np.any([True, False,False]))

True


In [ ]:
a=np.zeros((50,50))
print(a)
print(np.any(a!=0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
False


In [ ]:
x=np.arange(1,10)
print(np.mean(x))

5.0


In [ ]:
print(np.median(x))

5.0


In [ ]:
numbers = [1, 2, 3, 4, 5]
print(numbers)
array = np.array(numbers)
print(array)


[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
a=np.arange(2,11,1).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
a=np.array([[4,6],[2,1]])
b=np.sort(a,axis=0)
c=np.sort(a,axis=1)
print("original:\n",a)
print("column sort:\n",b)
print("row sort:\n",c)

original:
 [[4 6]
 [2 1]]
column sort:
 [[2 1]
 [4 6]]
row sort:
 [[4 6]
 [1 2]]


In [ ]:
a=np.array([[10,20,30],[20,40,50]])
print(np.ravel(a))

[10 20 30 20 40 50]
